name: Deploy Training Project

on:
  push:
    branches: ['master', 'main']

jobs:
  build:
    runs-on: ubunut-22.04
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Build docker imagesj
      run: docker build .
    - name: save image
      run: docker save -o trained_model.tar $(docker images | awk '{print $1}' | awk 'NR==2')
