name: Deploy Training Project

on:
  push:
    branches: ['master', 'main']

jobs:
       publish-odoo16-image:
              runs-on: ubuntu-latest
              steps:
                     - uses: actions/checkout@v2
                     - uses: docker/login-action@v1
                       with:
                              registry: ghcr.io
                              username: ${{ github.actor }}
                              password: ${{ secrets.GITHUB_TOKEN }}
                     - name: Build nvidia core module
                       run: |
                              timetag=(`date +%Y%M%d`)
                              cd core
                              docker build . --tag ghcr.io/viraweb/pt-nvidia-core:.${timetag} --tag ghcr.io/viraweb/pt-nvidia-core:22.01
                              docker push ghcr.io/viraweb/pt-nvidia-core:22.01
                              docker push ghcr.io/viraweb/pt-nvidia-core:.${timetag}
